In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# read the data
data = pd.read_csv("student.cleaned.data.csv")
data

school gender  age address famsize Pstatus  Medu  Fedu      Mjob  \
0       GP      F   18       U     GT3       A     4     4   at_home   
1       GP      F   17       U     GT3       T     1     1   at_home   
2       GP      F   15       U     LE3       T     1     1   at_home   
3       GP      F   15       U     GT3       T     4     2    health   
4       GP      F   16       U     GT3       T     3     3     other   
..     ...    ...  ...     ...     ...     ...   ...   ...       ...   
390     MS      M   20       U     LE3       A     2     2  services   
391     MS      M   17       U     LE3       T     3     1  services   
392     MS      M   21       R     GT3       T     1     1     other   
393     MS      M   18       R     LE3       T     3     2  services   
394     MS      M   19       U     LE3       T     1     1     other   

         Fjob  ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  \
0     teacher  ...      4        3      4     1     1      3        6   5   6   
1       other  ...      5        3      3     1     1      3        4   5   5   
2       other  ...      4        3      2     2     3      3       10   7   8   
3    services  ...      3        2      2     1     1      5        2  15  14   
4       other  ...      4        3      2     1     2      5        4   6  10   
..        ...  ...    ...      ...    ...   ...   ...    ...      ...  ..  ..   
390  services  ...      5        5      4     4     5      4       11   9   9   
391  services  ...      2        4      5     3     4      2        3  14  16   
392     other  ...      5        5      3     3     3      3        3  10   8   
393     other  ...      4        4      1     3     4      5        0  11  12   
394   at_home  ...      3        2      3     3     3      5        5   8   9   

     G3  
0     6  
1     6  
2    10  
3    15  
4    10  
..   ..  
390   9  
391  16  
392   7  
393  10  
394   9  

[395 rows x 33 columns]

In [4]:
data.head()

school gender  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  \
0     GP      F   18       U     GT3       A     4     4  at_home   teacher   
1     GP      F   17       U     GT3       T     1     1  at_home     other   
2     GP      F   15       U     LE3       T     1     1  at_home     other   
3     GP      F   15       U     GT3       T     4     2   health  services   
4     GP      F   16       U     GT3       T     3     3    other     other   

   ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0  ...      4        3      4     1     1      3        6   5   6   6  
1  ...      5        3      3     1     1      3        4   5   5   6  
2  ...      4        3      2     2     3      3       10   7   8  10  
3  ...      3        2      2     1     1      5        2  15  14  15  
4  ...      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [5]:
# Get the features needed for the regression from the data set
X = data[["traveltime", "studytime", "failures", "famrel", "freetime", "goout", "health"]]
X

traveltime  studytime  failures  famrel  freetime  goout  health
0             2          2         0       4         3      4       3
1             1          2         0       5         3      3       3
2             1          2         3       4         3      2       3
3             1          3         0       3         2      2       5
4             1          2         0       4         3      2       5
..          ...        ...       ...     ...       ...    ...     ...
390           1          2         2       5         5      4       4
391           2          1         0       2         4      5       2
392           1          1         3       5         5      3       3
393           3          1         0       4         4      1       5
394           1          1         0       3         2      3       5

[395 rows x 7 columns]

In [6]:
# Get your target
y = np.where(data['G3'] < 10, 0, 1)
y

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,

In [8]:
# training and test the data using only 10% as the test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.10, shuffle=False)

In [7]:
# import the MLPClassifier
from sklearn.neural_network import MLPClassifier

In [13]:
mlp = MLPClassifier(hidden_layer_sizes=(10,5,20), random_state=1, max_iter=300)

In [14]:
# Fit the train data
mlp.fit(X_train, y_train)

D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(10, 5, 20), max_iter=300, random_state=1)

In [15]:
# accuracy of a model
mlp.score(X_test, y_test)

0.675

In [16]:
# Check the class type
mlp.classes_

array([0, 1])

In [17]:
y_test

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [21]:
# Get the predicted values for Y
y_pred = mlp.predict(X_test)
y_pred

array([1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1])

In [22]:
pd.Series(y_pred)

0     1
1     1
2     0
3     1
4     1
5     0
6     0
7     1
8     1
9     1
10    0
11    1
12    1
13    1
14    1
15    0
16    1
17    1
18    1
19    1
20    1
21    0
22    1
23    1
24    1
25    1
26    1
27    1
28    0
29    0
30    1
31    1
32    1
33    1
34    0
35    0
36    1
37    0
38    1
39    1
dtype: int32

In [24]:
# y_test has true target values for test features, y_pred has predicted target values for test features
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.55      0.43      0.48        14
           1       0.72      0.81      0.76        26

    accuracy                           0.68        40
   macro avg       0.63      0.62      0.62        40
weighted avg       0.66      0.68      0.66        40



In [25]:
# The Logistic regression model gave a better accuracy score than the MLPClassifier.