In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data1 = pd.read_csv('AAPL.csv')
data1

Date        Open        High         Low       Close   Adj Close  \
0   2021-12-06  172.130005  179.630005  170.699997  179.449997  178.414520   
1   2021-12-13  181.119995  182.130005  169.690002  171.139999  170.152466   
2   2021-12-20  168.279999  176.850006  167.460007  176.279999  175.262802   
3   2021-12-27  177.089996  181.330002  177.070007  177.570007  176.545380   
4   2022-01-03  177.830002  182.940002  171.029999  172.169998  171.176529   
5   2022-01-10  169.080002  177.179993  168.169998  173.070007  172.071350   
6   2022-01-17  171.509995  172.539993  162.300003  162.410004  161.472855   
7   2022-01-24  160.020004  170.350006  154.699997  170.330002  169.347153   
8   2022-01-31  170.160004  176.240005  169.509995  172.389999  171.395248   
9   2022-02-07  172.860001  176.649994  168.039993  168.639999  167.880508   
10  2022-02-14  167.369995  173.339996  166.190002  167.300003  166.546555   
11  2022-02-21  164.979996  166.690002  152.000000  164.850006  164.107590   
12  2022-02-28  163.059998  168.910004  161.970001  163.169998  162.435135   
13  2022-03-07  163.360001  165.020004  154.500000  154.729996  154.033157   
14  2022-03-14  151.449997  164.479996  150.100006  163.979996  163.241516   
15  2022-03-21  163.509995  175.279999  163.009995  174.720001  173.933136   
16  2022-03-28  172.169998  179.610001  171.940002  174.309998  173.524979   
17  2022-04-04  174.570007  178.490005  169.199997  170.089996  169.323975   
18  2022-04-11  168.710007  171.270004  165.039993  165.289993  164.545609   
19  2022-04-18  163.919998  171.529999  161.500000  161.789993  161.061356   
20  2022-04-25  161.119995  166.199997  155.380005  157.649994  156.940002   
21  2022-05-02  156.710007  166.479996  153.270004  157.279999  156.571686   
22  2022-05-09  154.929993  156.740005  138.800003  147.110001  146.662643   
23  2022-05-16  145.550003  149.770004  132.610001  137.589996  137.171600   
24  2022-05-23  137.789993  149.679993  137.139999  149.639999  149.184952   
25  2022-05-30  149.070007  151.740005  144.460007  145.380005  144.937912   
26  2022-06-06  147.029999  149.869995  137.059998  137.130005  136.713013   
27  2022-06-13  132.869995  137.339996  129.039993  131.559998  131.159927   
28  2022-06-20  133.419998  141.910004  133.320007  141.660004  141.229233   
29  2022-06-27  142.699997  143.490005  133.770004  138.929993  138.507507   
30  2022-07-04  137.770004  147.550003  136.929993  147.039993  146.592850   
31  2022-07-11  145.669998  150.860001  142.119995  150.169998  149.713333   
32  2022-07-18  150.740005  156.279999  146.699997  154.089996  153.621414   
33  2022-07-25  154.009995  163.630005  150.800003  162.509995  162.015808   
34  2022-08-01  161.009995  167.190002  159.630005  165.350006  164.847198   
35  2022-08-08  166.369995  172.169998  163.250000  172.100006  171.814987   
36  2022-08-15  171.520004  176.149994  171.309998  171.520004  171.235947   
37  2022-08-22  169.690002  171.050003  163.559998  163.619995  163.349014   
38  2022-08-29  161.149994  162.899994  154.669998  155.809998  155.551956   
39  2022-09-05  156.470001  157.820007  152.679993  157.369995  157.109375   
40  2022-09-12  159.589996  164.259995  148.369995  150.699997  150.450424   
41  2022-09-19  149.309998  158.740005  148.559998  150.429993  150.180862   
42  2022-09-26  149.660004  154.720001  138.000000  138.199997  137.971115   
43  2022-10-03  138.210007  147.539993  137.690002  140.089996  139.857986   
44  2022-10-10  140.419998  144.520004  134.369995  138.380005  138.150833   
45  2022-10-17  141.070007  147.850006  140.270004  147.270004  147.026108   
46  2022-10-24  147.190002  157.500000  144.130005  155.740005  155.482086   
47  2022-10-31  153.160004  155.449997  134.380005  138.380005  138.150833   
48  2022-11-07  137.110001  150.009995  134.589996  149.699997  149.699997   
49  2022-11-14  148.970001  153.589996  146.149994  151.289993  151.289993   
50  2022-11-21  150.160004  151.

In [6]:
data1 = data1.iloc[:9] #get the first 9 rows from the dataframe

In [7]:
data1

Date        Open        High         Low       Close   Adj Close  \
0  2021-12-06  172.130005  179.630005  170.699997  179.449997  178.414520   
1  2021-12-13  181.119995  182.130005  169.690002  171.139999  170.152466   
2  2021-12-20  168.279999  176.850006  167.460007  176.279999  175.262802   
3  2021-12-27  177.089996  181.330002  177.070007  177.570007  176.545380   
4  2022-01-03  177.830002  182.940002  171.029999  172.169998  171.176529   
5  2022-01-10  169.080002  177.179993  168.169998  173.070007  172.071350   
6  2022-01-17  171.509995  172.539993  162.300003  162.410004  161.472855   
7  2022-01-24  160.020004  170.350006  154.699997  170.330002  169.347153   
8  2022-01-31  170.160004  176.240005  169.509995  172.389999  171.395248   

      Volume  
0  341325300  
1  769299200  
2  359176900  
3  340248100  
4  481949000  
5  422655700  
6  400041100  
7  688258600  
8  458553300

In [8]:
data2 = data1['Close']

In [9]:
data2

0    179.449997
1    171.139999
2    176.279999
3    177.570007
4    172.169998
5    173.070007
6    162.410004
7    170.330002
8    172.389999
Name: Close, dtype: float64

In [10]:
type(data2)

pandas.core.series.Series

In [14]:
data2 = data2.values

In [15]:
type(data2)

numpy.ndarray

In [16]:
data2

array([179.449997, 171.139999, 176.279999, 177.570007, 172.169998,
       173.070007, 162.410004, 170.330002, 172.389999])

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler = MinMaxScaler()

In [19]:
data2res = data2.reshape(-1, 1)

In [20]:
data2res

array([[179.449997],
       [171.139999],
       [176.279999],
       [177.570007],
       [172.169998],
       [173.070007],
       [162.410004],
       [170.330002],
       [172.389999]])

In [21]:
type(data2)

numpy.ndarray

In [22]:
data3 = scaler.fit_transform(data2res)

In [23]:
data3.shape

(9, 1)

In [24]:
data3

array([[1.        ],
       [0.51232386],
       [0.81396718],
       [0.8896719 ],
       [0.57276984],
       [0.62558729],
       [0.        ],
       [0.46478881],
       [0.5856807 ]])

In [25]:
from numpy import array

In [26]:
def split_sequence(sequence, time_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + time_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [27]:
#convert the 2D array of data to 1D array
data3 = data3.flatten()

In [28]:
data3

array([1.        , 0.51232386, 0.81396718, 0.8896719 , 0.57276984,
       0.62558729, 0.        , 0.46478881, 0.5856807 ])

In [29]:
# split the data into sample rows
# specify the data and the number of time steps to the function split_sequence
# The returned value in X will have the feature columns. 
# The returned value in y will have the target column. 
# The number of feature columns is equal to the number of time steps
X, y = split_sequence(data3, 3)
# X will have 6 rows, 3 feature columns (due to 3 time steps). 
# y will have the target column

In [30]:
X

array([[1.        , 0.51232386, 0.81396718],
       [0.51232386, 0.81396718, 0.8896719 ],
       [0.81396718, 0.8896719 , 0.57276984],
       [0.8896719 , 0.57276984, 0.62558729],
       [0.57276984, 0.62558729, 0.        ],
       [0.62558729, 0.        , 0.46478881]])

In [31]:
y

array([0.8896719 , 0.57276984, 0.62558729, 0.        , 0.46478881,
       0.5856807 ])

In [32]:
# data summary
for i in range(len(X)):
	print(X[i], ' ', y[i])

[1.         0.51232386 0.81396718]   0.8896719030342339
[0.51232386 0.81396718 0.8896719 ]   0.5727698362317408
[0.81396718 0.8896719  0.57276984]   0.6255872875065158
[0.8896719  0.57276984 0.62558729]   0.0
[0.57276984 0.62558729 0.        ]   0.4647888059578449
[0.62558729 0.         0.46478881]   0.5856806983430101


In [33]:
import tensorflow as tf
#use these two lines when you use tensorflow models.
#This woud avoid several warnings and errors
tf.config.run_functions_eagerly(True)
tf.data.experimental.enable_debug_mode()

In [34]:
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

In [35]:
# build an LSTM RNN using a sequential model.

model1 = Sequential([
    #model expects every row of feature data with shape as input_shape
    # input_shape=(3, 1) implies 3 feature columns and 1 target column  
    layers.InputLayer(input_shape=(3, 1)),
    
    # 50 LSTM units in the hidden layer, 
    # relu activation function at each unit
    layers.LSTM(50, activation='relu'), #hidden layer
    
    # 1 Dense unit in the output layer since there is  
    # only 1 class of value (i.e. number) in the target column
    layers.Dense( 1 ) #output layer
])

In [36]:
# compile the model using adam optimizer, mean_squared_error loss-function 
model1.compile(optimizer='adam', 
              loss='mean_squared_error')

In [37]:
X.shape

(6, 3)

In [38]:
X.shape[0]

6

In [39]:
X.shape[1]

3

In [40]:
Xrs = X.reshape(X.shape[0], X.shape[1], 1)  # Need to reshape X to 3D (6, 3, 1) for the fit function

In [41]:
Xrs.shape

(6, 3, 1)

In [42]:
Xrs

array([[[1.        ],
        [0.51232386],
        [0.81396718]],

       [[0.51232386],
        [0.81396718],
        [0.8896719 ]],

       [[0.81396718],
        [0.8896719 ],
        [0.57276984]],

       [[0.8896719 ],
        [0.57276984],
        [0.62558729]],

       [[0.57276984],
        [0.62558729],
        [0.        ]],

       [[0.62558729],
        [0.        ],
        [0.46478881]]])

In [43]:
# fit model
model1.fit(Xrs, y,  
          verbose=0,
          epochs=100)

In [44]:
score = model1.evaluate(Xrs, y, verbose=0) #finding accuracy of the model

In [45]:
score #In this case, score only has a scalar test loss 
       #(since the model has only 1 class of value i.e. number)

0.07020335644483566

In [46]:
print("Test loss:", score)

Test loss: 0.07020335644483566


In [47]:
predictions = model1.predict(Xrs) #using the same true feature data for prediction of the target values

1/1 [==============================] - 0s 60ms/step


In [48]:
predictions

array([[0.57622784],
       [0.55025804],
       [0.5681646 ],
       [0.537389  ],
       [0.42501628],
       [0.41597497]], dtype=float32)

In [49]:
pd.Series(y) # y has true target values

0    0.889672
1    0.572770
2    0.625587
3    0.000000
4    0.464789
5    0.585681
dtype: float64